### ISSUE TITLE
Пофиксить много чего:

### ISSUE THREAD

**Issue by GeorgNation** [veselcraft/NotAYTMusic#1]
1. Принимать только WAV
2. Возможность вставлять имена композиторов трека (однако из-за моей лени я хз)
3. Поправить ещё ошибки

**Comment by veselcraft** [comment]
>перечислил ошибки
>"поправить ещё ошибки"

а зачем только wav принимать? оно всё равно в aac ужмётся

с именами композиторов да, чуть беда. оно принимает значения только из самого mp3 файла, а если их нет, то хрен нормально сгенерятся видео. но я это делал ориентировачно на свою аудиобиблиотеку - у меня там всё оформлено
